### ISSUE TITLE
Google oauth account throwing unauthorized exception.

### ISSUE THREAD

**Issue by Surered** [adrielcafe/AndroidGoogleOAuth#2]
I tried to configure google oauth account but there is no information found for the APP Secret key in the google developer console.

The exception I am getting.
com.github.scribejava.core.exceptions.OAuthException: Response body is incorrect. Can't extract a '"access_token"\s_:\s_"(\S*?)"' from this: '{
  "error": "invalid_client",
 "error_description": "Unauthorized"
}

**Comment by adrielcafe** [comment]
Probably you created an Android credential (that doesn't have secret). This lib only works with [Web](https://developers.google.com/youtube/analytics/registering_an_application#web-applications) and [Other](https://developers.google.com/youtube/analytics/registering_an_application#other-installed-application-credentials) credentials. 
- In the **Credentials tab**, select the **Create credentials** drop-down list, and choose **OAuth client ID**
- Under **Application type**, select **Web application** or **Other**.
- Now you can get your keys:

![credentials](https://cloud.githubusercontent.com/assets/2512298/17373942/c77dc5ec-5980-11e6-9f27-7507977a86e2.png)

Hope this help. If not, please let me know.

**Comment by Surered** [comment]
Sorry I checked it later thanks for the swift response.
