### ISSUE TITLE
"You are not logged in: You are not logged in. Please log in and try again."

### ISSUE THREAD

**Issue by samk17cmutpm** [adrielcafe/AndroidGoogleOAuth#3]
I have an error with facebook 
"You are not logged in: You are not logged in. Please log in and try again."

**Comment by adrielcafe** [comment]
Hi @samk17cmutpm,
Seems like a facebook app settings problem. Could you check [this](https://github.com/magus/react-native-facebook-login/issues/48) and [this](http://stackoverflow.com/a/31901140)?
