### ISSUE TITLE
Birthday in SocialUser

### ISSUE THREAD

**Issue by lionelatrecisio** [adrielcafe/AndroidGoogleOAuth#4]
Hello,

First of all, great job!

Is it possible to add the birthday in the SocialUser class? In your demo you ask for it for both Google and Facebook, but we can't get the response in the user returned.

Thanks a lot,

Lionel

**Comment by adrielcafe** [comment]
Done!

Please update to the [latest release](https://github.com/adrielcafe/AndroidOAuth/releases/latest) and enjoy 😃

**Comment by lionelatrecisio** [comment]
Thank you very much!
